language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: heroku
  directory: dist
  app: vue-performance-test
  api_key:
    secure: EOBAb/ni5MbkQNbMLNayD4yI+JppS8uBi6LkcjKEOlCEe90Il9xOcLSrRkc7/g5p3XgHOs4+qLI/wMUr+N2XbEjH9zuQ3+oXlFK0TtGfULtQfCEspnXY883p9GAclrG5bLzh41qnj6NMJCSNDZ0Qq45R+A3LAFn+HselGh55nHKywePz3tSPZEzod6emYyRszfbYR9MqboxzaPpprd2CVudgMHhUL2Fc2tDLZU0rdGRpAyoyoyQS4WTJDEUYwhqdW5Ep2Zx4RqNPTGvDOTV+lkO37MRVJJ/c9sFddDBhfmKTWTYRpR1B+luQdq1/buu16PuESw2415rElriwHW2beeNhOeELqNtfOAVBRn6qKhoUVd537JRsiMHb3L2t+H5c0amhqGMIgvKw79odksKSSES8dtxG6orlS/VFN3fQNIYiSy+mdOtwC2+nlcE6zx4gOa3AlFmtbqCnbRF/466TBhW6a8+FTwhfZM1HguTgUw3erwqzR5UwmRQGnMGi43lJ6tw5v+BX3bJg7/H9xMbxpoXzflB0VBGRKLRMfTa8WCF1RSoX8KLA6GXXegbM9WWVWVw9+ATB6MN1nQa1xiMdfNHQIpsgZh5OdtmWlT7GI+bCvDWVT2TrzzX6flYYWUILVrGjm0D1+fgYkjHJu3U3VifIQsgPXXpjnwT7eELtmqs=
  on:
    repo: Tiico/vue-performance-test
    branch: master
